version: "3.7"
services:
  frontend:
    build: 
      context: ./angular-frontend
    network_mode: "host"
    volumes:
      - ./angular-frontend/src:/app/src
  backend:
    build:
      context: ./py-backend
    network_mode: "host"
    volumes:
      - /var/lib/pymdb:/var/lib/pymdb
